### ISSUE TITLE
Experiment 2 Diagam Is Incorrect

### ISSUE THREAD

**Issue by marlabrizel** [sparkfun/Inventors_Kit_For_Photon_Experiments#3]
In Experiment 2 ("With the Touch of a Button"), the PNG indicates that the jumper should be connected on row 7 of the breadboard. However, it should instead be on row 6, to line up with the bottom of the push button. 

See below highlighted screenshot; the blue jumper should move up one position on the breadboard so that there is only one empty position between it and the black jumper (rather than the indicated two).

![image](https://cloud.githubusercontent.com/assets/6632025/21083983/0d11850a-bfb9-11e6-8291-2f11c24001fa.png)

Thank you!

**Comment by JoelEB** [comment]
Fixed the diagram. Thanks for the notification, and thanks for reading!
